config/routes.rb
Wandermust::Application.routes.draw do
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"
  match "destinations/complete" => 'destinations#complete', :as => "complete"

  get "destinations/:id/save/" => 'destinations#save', :as => 'save_destination'

  resources :users
  resources :sessions, :except => [:edit, :update, :index]
  resources :destinations, :except => [:edit, :update, :delete]
  resources :favorites, :only => [:destroy]

  root :to => 'destinations#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :destinations, through: :favorites
  has_many :favorites, dependent: :destroy

  attr_accessible :email, :first_name, :password, :password_confirmation, :destination_id

  validates :email, :uniqueness => true

  validates_presence_of :first_name
  validates_presence_of :email
  validates_presence_of :password, :on => :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_authentication, :only => [:new, :create]
  skip_before_filter :require_admin_authentication, :only => [:new, :create, :edit, :update, :show]

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  def show
    @user = User.find(session[:user_id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        if !params[:destination_id].nil?
          @destination = Destination.find(params[:destination_id]) #if a destination param comes in (i.e. page was rendered from a non-logged-in user that wanted to sign up)
          if !@user.destinations.include?(@destination)
            @user.destinations << @destination #push destination into bridge table
          else
            flash[:alert] = "That favorite is already in your list."
          end
        end
        format.html { redirect_to @user, notice: 'Welcome to your new Account!' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { redirect_to root_path, alert: 'There was an error when signing up, please try again.' }
        format.js
      end
    end
  end

  def update
    @user = User.find(session[:user_id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Your account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.js
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div id="sign_in">
  <h4>New User Sign up</h4>
  <br>
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name, "Your name" %>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <% if !@destination.nil? %>
      <input type="hidden" name="destination_id" value="<%= @destination.id %>">
    <% end %>
    <div class="actions">
      <%= f.submit "Register", :class => "btn btn-info"%>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<p>Or, Go Back to Your <%= link_to 'Profile', @user %></p>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<h1>Your Saved Destinations</h1>

<div id="container_favorites">
  <table class="table table-hover">
    <thead>
      <th>Destination</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
    </thead>

    <tbody>
      <% @user.favorites.each do |favorite| %>
        <tr class="">
          <td><%= favorite.destination.address %></td>
          <td><%= favorite.destination.latitude %></td>
          <td><%= favorite.destination.longitude %></td>
          <td><%= link_to 'Show', favorite.destination %></td>
          <td><%= link_to 'Remove', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br />


<%= link_to 'Edit your Profile', edit_user_path(@user) %> |
<%= link_to 'Back to Home', destinations_path %>