config/routes.rb
Wandermust::Application.routes.draw do
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"
  match "destinations/complete" => 'destinations#complete', :as => "complete"

  get "destinations/:id/save/" => 'destinations#save', :as => 'save_destination'

  resources :users
  resources :sessions, :except => [:edit, :update, :index]
  resources :destinations, :except => [:edit, :update, :delete]
  resources :favorites, :only => [:destroy]

  root :to => 'destinations#index'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_many :users, through: :favorites
  has_many :favorites, dependent: :destroy

  attr_accessible :latitude, :longitude, :address, :user_id


  reverse_geocoded_by :latitude, :longitude do |destination,results|
    if geo = results.first
      if !geo.city.blank? && !geo.country.blank?
        destination.address = "#{geo.city}, #{geo.state}, #{geo.country}"
        if (destination.address.blank? || destination.address == "0" || destination.address == 0 || destination.address == "2" || destination.address == 2)
          destination.address = 0
        end
      else
        destination.address = 1
      end
    else
      destination.address = 2 #when this occurs, there is a potential error (query limit/etc) so needs special treatment
    end
  end
  after_validation :reverse_geocode


  def get_random_coordinates
    update_attributes(:longitude => (rand*(360)-180), :latitude => (rand*(180)-90))
    return  #without this, I was getting back "true"
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  require "open-uri"
  require 'wikipedia'

  skip_before_filter :require_authentication
  skip_before_filter :require_admin_authentication

  def index
  end

  def complete
    @destinations = Destination.all
  end

  def create
    # Goal: Use Geocoder to pull back a city, if no city returns, create new random coordinates

    @destination = Destination.new

    #in case the geocoder fails, only try this many times before breaking loop
    max_geocode_fails = 15

    #get random coordinates, which also triggers geocoder gem reverse geocode
    @destination.get_random_coordinates

    # make sure the destination has a valid city returned, and if it doesn't, just delete destination and try again
    #in future, see if I can do this before saving a record to DB
    if [0,1,2,"0","1","2"].include?(@destination.address)
      counter = 1
      until ( ![0,1,2,"0","1","2"].include?(@destination.address) || counter == max_geocode_fails )
        @destination.destroy
        @destination = Destination.new
        @destination.get_random_coordinates
        counter = counter + 1
      end
    end

    # geocoder configured to google only allows 2500 q/day apparently. consider a different config

    # if it does fail/max out, leverage the existing db
    if counter == max_geocode_fails
      @destination.destroy

      #pick a random destination from the DB instead
      all_saved_ids = []
      destinations = Destination.all

      destinations.each do |destination|
        all_saved_ids << destination.id
      end
      @destination = Destination.find(all_saved_ids.sample)
    end

    respond_to do |format|
      #if we hit the limit due to geocoder fail, don't overwrite the existing db destination by saving it.
      if counter == max_geocode_fails
        format.html { redirect_to @destination }
        format.js
      else
        if @destination.save
          format.html { redirect_to @destination }
          format.js
        else
          format.html { render action: "index" }
          format.js
        end
      end
    end
  end

  def show
    @destination = Destination.find(params[:id])

    if !session[:user_id].blank?  #only used to see if the favorite is owned by logged in user
      @user = User.find(session[:user_id])
    end

    begin
      response = RubyWebSearch::Google.search(:query => "#{@destination.address} site:en.wikipedia.org").results.first[:url]
      if response.include?("User")
        raise
      end
      wiki_content = Nokogiri::HTML(open(response))
      summary = wiki_content.css("#mw-content-text p")[0].content
      if (summary.blank? || summary.include?("Coordinates") || summary.include?("www") || summary.length < 52)
        summary = wiki_content.css("#mw-content-text p")[1].content
        if (summary.include?("may refer to") || summary.blank? || summary.include?("Coordinates") || summary.include?("www"))
          raise
        else
          @summary = summary
        end
      else
        @summary = summary
      end
    rescue
      begin
        response = RubyWebSearch::Google.search(:query => "#{@destination.address.split(", ")[0]}, #{@destination.address.split(", ")[2]} site:en.wikipedia.org").results.first[:url]
        if response.include?("User")
          raise
        end
        wiki_content = Nokogiri::HTML(open(response))
        summary = wiki_content.css("#mw-content-text p")[0].content
        if (summary.blank? || summary.include?("Coordinates") || summary.include?("www") || summary.length < 52)
          summary = wiki_content.css("#mw-content-text p")[1].content
          if (summary.include?("may refer to") || summary.blank? || summary.include?("Coordinates") || summary.include?("www"))
            raise
          else
            @summary = summary
          end
        else
          @summary = summary
        end
      rescue
        begin
          response = RubyWebSearch::Google.search(:query => "#{@destination.address.split(", ")[1]}, #{@destination.address.split(", ")[2]} site:en.wikipedia.org").results.first[:url]
          if response.include?("User")
            raise
          end
          wiki_content = Nokogiri::HTML(open(response))
          summary = wiki_content.css("#mw-content-text p")[0].content
          if (summary.blank? || summary.include?("Coordinates") || summary.include?("www") || summary.length < 52)
            summary = wiki_content.css("#mw-content-text p")[1].content
            if (summary.include?("may refer to") || summary.blank? || summary.include?("Coordinates") || summary.include?("www"))
              raise
            else
              @summary = summary
            end
          else
            @summary = summary
          end
        rescue
          begin
            wiki_content = Nokogiri::HTML(open("http://en.wikipedia.org/wiki/#{@destination.address.split(", ")[0].titleize.gsub(" ", "_")}"))
            summary = wiki_content.css("#mw-content-text p")[0].content
            if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to") || summary.include?("www") || summary.length < 52)
              summary = wiki_content.css("#mw-content-text p")[1].content
              if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to"))
                raise
              else
                @summary = summary
              end
            else
              @summary = summary
            end
          rescue
            begin
              wiki_content = Nokogiri::HTML(open("http://en.wikipedia.org/wiki/#{@destination.address.split(", ")[0].titleize.split(" ")[0]}"))
              summary = wiki_content.css("#mw-content-text p")[0].content
              if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to") || summary.include?("www") || summary.length < 52)
                summary = wiki_content.css("#mw-content-text p")[1].content
                if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to"))
                  raise
                else
                  @summary = summary
                end
              else
                @summary = summary
              end
            rescue
              begin
              wiki_content = Nokogiri::HTML(open("http://en.wikipedia.org/wiki/#{@destination.address.split(", ")[1].titleize.gsub(" ", "_")}"))
              summary = wiki_content.css("#mw-content-text p")[0].content
              if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to") || summary.include?("www") || summary.length < 52)
                summary = wiki_content.css("#mw-content-text p")[1].content
                if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to"))
                  raise
                else
                  @summary = summary
                end
              else
                @summary = summary
              end
              rescue
                begin
                wiki_content = Nokogiri::HTML(open("http://en.wikipedia.org/wiki/#{@destination.address.split(", ")[1].titleize.split(" ")[0]}"))
                summary = wiki_content.css("#mw-content-text p")[0].content
                if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to") || summary.include?("www") || summary.length < 52)
                  summary = wiki_content.css("#mw-content-text p")[1].content
                  if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to"))
                    raise
                  else
                    @summary = summary
                  end
                else
                  @summary = summary
                end
                rescue
                  begin
                  wiki_content = Nokogiri::HTML(open("http://en.wikipedia.org/wiki/#{@destination.address.split(", ")[2].titleize.gsub(" ", "_")}"))
                  summary = wiki_content.css("#mw-content-text p")[0].content
                  if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to") || summary.include?("www") || summary.length < 52)
                    summary = wiki_content.css("#mw-content-text p")[1].content
                    if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to"))
                      raise
                    else
                      @summary = summary
                    end
                  else
                    @summary = summary
                  end
                  rescue
                    wiki_content = Nokogiri::HTML(open("http://en.wikipedia.org/wiki/#{@destination.address.split(", ")[2].titleize.split(" ")[0]}"))
                    summary = wiki_content.css("#mw-content-text p")[0].content
                    if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to") || summary.include?("www") || summary.length < 52)
                      summary = wiki_content.css("#mw-content-text p")[1].content
                      if (summary.blank? || summary.include?("Coordinates") || summary.include?("may refer to"))
                        raise
                      else
                        @summary = summary
                      end
                    else
                      @summary = summary
                    end
                  end
                end
              end
            end
          end
        end
      end
    end

    if !response.nil?
      page = Wikipedia.find(response)
      @photo_urls = []
      if !page.image_urls.blank?
        p = page.image_urls
        p.reject!{|url| url == nil }
        p.each do |url|
          if !url.include?("Compass") && !url.include?("Ambox") && !url.include?("A-") && !url.include?("Magnify")
            @photo_urls << url
          end
        end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/complete.html.erb
<h1>Recent Destinations</h1>


<div id='map_complete' class="span10"></div>
<script>
var map = L.mapbox.map('map_complete', 'examples.map-20v6611k');
map.addLayer(L.tileLayer('http://tile.stamen.com/watercolor/{z}/{x}/{y}.jpg'));
map.setView([30, -0], 1);
var d = [];
<% most_recent_destinations_for_map.shuffle.each do |destination| %>
  d.push({
      type: 'Feature',
      properties: {
          title: '<%= destination.address.split(", ")[0] %>, <%= destination.address.split(", ")[2] %>',
          'marker-size': 'small',
          'marker-symbol': 'embassy',
          'marker-color': '#77C99B',
          url: '<%= destination_url(destination) %>'
      },
      geometry: {
          type: 'Point',
          coordinates: [<%= destination.longitude %>, <%= destination.latitude %>]
      }
  })
<% end %>

var geoJson = {
    type: 'FeatureCollection',
    features: d

};


map.markerLayer.setGeoJSON(geoJson);

var markers = $('.leaflet-marker-pane img')
var delay = 0;
$.each(markers, function(k,v) {
  var marker = $(v);
  delay += 50;
  setTimeout(function() {
    marker.show();
  }, delay);
});



map.markerLayer.on('mouseover', function(e) {
    e.layer.openPopup();
});
map.markerLayer.on('mouseout', function(e) {
    e.layer.closePopup();
});
map.markerLayer.on('click', function(e) {
    e.layer.unbindPopup();
    window.open(e.layer.feature.properties.url,"_parent");
});
</script>

<h5>Note, the wander button choose a mathematically random place on Earth, but will ignore the ocean and locations without a city name (sorry Antarctica...)</h5>

app/views/destinations/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <div id="homepage">
      <h1>Discover your World</h1>
      <br>
      <p>You are only lost if you have stopped searching</p>
        <br>

        <%= link_to "Wander...", destinations_path, :method => "POST", :id => "start_journey", :class => "btn btn-primary btn-block btn-large" %>
    </div>
  </div>
</div>

app/views/destinations/show.html.erb
<h1 class="d<%= @destination.id %>"><%= @destination.address %></h1>
<h5>Latitude: <%= @destination.latitude.round(9) %>,  Longitude: <%= @destination.longitude.round(9) %></h5>
<p id="destination_content"><%= remove_footnote_tags(@summary) %></p>

<div class="row-fluid">
    <div id='map' class="dark span9"></div>

    <div  class="span3">
            <% if current_user == nil %>
                <div id="save_w_modal" class= "save_destination_button"><%= link_to 'Save this Destination', "#loginModal", :id => "", :class =>"btn btn-small btn-success btn-block", :data => {:remote => true, :toggle => "modal"} %></div>
                <div id="save_without_modal" class=" save_destination_button hide1"><%= link_to 'Save this Destination', save_destination_path, :id => "", :class =>"btn btn-small btn-block btn-success" %></div>
            <% else %>
                <% if @destination.users.include?(current_user) %>
                    <div class= "save_destination_button"><%= link_to 'One of your Favorites', user_path(@user), :id => "", :class =>"btn btn-small btn-block btn-inverse" %></div>
                <% else %>
                  <div class= "save_destination_button"><%= link_to 'Save this Destination', save_destination_path, :id => "", :class =>"btn btn-small btn-block btn-success" %></div>
                <% end %>
            <% end %>

        <% if @photo_urls.present? %>
        <div id="side_photo_container">
            <% @photo_urls.each do |photo| %>
                <%= image_tag(photo, :class => "wiki_photos") %>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

<script type='text/javascript'>

    var dimensions = null;

    if ($(window).width() <= 480) {
        dimensions = 100
    }
    else {
        dimensions = 150
    }


 var map = L.mapbox.map('map', 'examples.map-qfyrx5r8')
     .addControl(L.mapbox.geocoderControl('examples.map-qfyrx5r8'))
     .setView([<%= @destination.latitude %>, <%= @destination.longitude %>], 6)
     .on('ready', function() {
       new L.Control.MiniMap(L.mapbox.tileLayer('examples.map-b70jh5xu'), {height: dimensions, width:dimensions})
         .addTo(map);
      });

 var feature = {
     type: 'Feature',
     geometry: {
         type: 'Point',
         coordinates: [<%= @destination.longitude %>, <%= @destination.latitude %>]
     },
     properties: {
         title: "<%= @destination.address.split(", ")[0] %>, <%= @destination.address.split(", ")[2] %>",
         description: "",
         "marker-symbol": "star",
         "marker-color": "#ff0000",
     }
 };

 map.markerLayer.setGeoJSON(feature);

 var marker = $('.leaflet-marker-pane img')
 marker.show();

</script>