config/routes.rb
Wandermust::Application.routes.draw do
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"
  match "destinations/complete" => 'destinations#complete', :as => "complete"

  get "destinations/:id/save/" => 'destinations#save', :as => 'save_destination'

  resources :users
  resources :sessions, :except => [:edit, :update, :index]
  resources :destinations, :except => [:edit, :update, :delete]
  resources :favorites, :only => [:destroy]

  root :to => 'destinations#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wandermvst</title>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.3/leaflet.css" />
   <!--[if lte IE 8]>
       <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.3/leaflet.ie.css" />
   <![endif]-->
   <script src="http://cdn.leafletjs.com/leaflet-0.6.3/leaflet.js"></script>
  <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
    <script src='//api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.js'></script>
    <link href='//api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.css' rel='stylesheet' />
    <!--[if lte IE 8]>
      <link href='//api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.ie.css' rel='stylesheet' >
    <![endif]-->
    <%= stylesheet_link_tag "Control.MiniMap.css" %>
    <%= javascript_include_tag "Control.MiniMap.js" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Fredericka+the+Great' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=IM+Fell+English' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-42810021-1', 'wandermvst.com');
    ga('send', 'pageview');

  </script>

</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">

        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <!-- Be sure to leave the brand out there if you want it shown -->
        <a class="brand" href="/">Wandermvst</a>

        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            <% if current_user %>
              <li class=""><%= link_to "Howdy, #{current_user.first_name}", user_path(current_user), :class => "nav" %></li>
              <li class=""><%= link_to "Log Out", logout_path, :class => "nav" %></li>
            <% else %>
              <li id ="login_not_modal_small"><%= link_to "Log In", new_session_path, :class => "nav" %></li>
              <li id = "login_modal_big"><%= link_to "Log In", "#loginModal", :class => "nav", :data => {:remote => true, :toggle => "modal"}  %></li>
            <% end %>
          </ul>
          <!-- .nav, .navbar-search, .navbar-form, etc -->
        </div>

      </div>
    </div>
  </div>
  <div class="container-fluid">

    <% unless flash[:notice].blank? %>
      <p id="flash_notice"><%= flash[:notice] %></p>
    <% end %>

    <% unless flash[:alert].blank? %>
      <p id="flash_alert"><%= flash[:alert] %></p>
    <% end %>

    <% if !current_user %>
      <div id="loginModal" class="modal hide fade span6" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="loginModalLabel">Sign up or Login Below</h3>
        </div>
        <div class="modal-body">
          <form class="form-horizontal well span4" href="remote.html" data-async data-target="/" action="/users" method="POST">
            <fieldset>
              <%= render :partial => 'users/form', :locals => {:user => @user}  %>
            </fieldset>
          </form>

          <form class="form-horizontal well span4" href="remote.html" data-async data-target="/" action="/sessions" method="POST">
            <fieldset>
              <%= render 'sessions/form'  %>
            </fieldset>
          </form>
        </div>
      </div>
    <% end %>

    <div id="globus" class=""><%= image_tag(asset_path('crd_logo_new.gif')) %></div>

    <div class="row-fluid">
      <div class="span9 well">

        <%= yield %>

      </div>
      <div class="span3 well">
        <ul class="nav nav-list">
          <%= link_to "See the World", complete_path, :id => "world_map_link", :class => "btn btn-warning btn-block btn-medium" %>
          <li class="divider"></li>
          <li class="nav-header">Top Destinations</li>
          <li class="divider"></li>
          <ol id="top_list">
            <% top_destinations_list.take(5).each do |destination| %>
              <li class="d<%= destination.id %>"><%= link_to "#{destination.address}", destination_path(destination) %></li>
            <% end %>
          </ol>
          <li class="divider"></li>
          <li class="nav-header">Trending Destinations</li>
          <!-- This will be saved by timestamp over the last 1 day -->
          <li class="divider"></li>
          <ol id="top_list">
            <% trending_destinations_list.take(3).each do |destination| %>
              <% if destination.favorites.size != 0  %>
                <li class="d<%= destination.id %>"><%= link_to "#{destination.address}", destination_path(destination) %></li>
              <% end %>
            <% end %>
          </ol>
          <li class="divider"></li>
          <%= link_to "Wander...", destinations_path, :method => "POST", :id => "wander_button", :class => "btn btn-primary btn-block btn-large" %>
        </ul>
      </div>
    </div>
  </div>





</body>
</html>